import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

import '../../domain/exceptions.dart';
import '../../domain/models/land_ring.dart';
import '../../domain/models/world_city.dart';
import '../../domain/repositories/world_map_repository.dart';

/// Loader for asset string data (replaceable in tests)
typedef AssetStringLoader = Future<String> Function(String key);

Future<String> _rootBundleStringLoader(String key) =>
    rootBundle.loadString(key);

/// Repository implementation loading the bundled world map assets
/// (assets/map/).
///
/// Asset formats (generated by tool/catalog_converter/convert_worldmap.dart):
/// - world_cities.json: `[[name, country, lat, lon, capital(0/1)], ...]`
/// - world_land.json: `[[[lon,lat], ...], ...]` (outer polygon rings)
class WorldMapLoader implements WorldMapRepository {
  WorldMapLoader({
    AssetStringLoader? loader,
    this.citiesAssetKey = 'assets/map/world_cities.json',
    this.landAssetKey = 'assets/map/world_land.json',
  }) : _loader = loader ?? _rootBundleStringLoader;

  final AssetStringLoader _loader;
  final String citiesAssetKey;
  final String landAssetKey;

  @override
  Future<List<WorldCity>> loadCities() async {
    try {
      final rows = jsonDecode(await _loader(citiesAssetKey)) as List;
      return [
        for (final row in rows.cast<List<dynamic>>())
          WorldCity(
            name: row[0] as String,
            country: row[1] as String,
            latitudeDeg: (row[2] as num).toDouble(),
            longitudeDeg: (row[3] as num).toDouble(),
            isCapital: (row[4] as num) == 1,
          ),
      ];
    } on FormatException catch (e) {
      throw CatalogCorruptedException('Invalid world city data format: $e');
    } on TypeError catch (e) {
      throw CatalogCorruptedException('Invalid world city data format: $e');
    }
  }

  @override
  Future<List<LandRing>> loadLandRings() async {
    try {
      final rings = jsonDecode(await _loader(landAssetKey)) as List;
      return [
        for (final ring in rings.cast<List<dynamic>>())
          LandRing(
            [
              for (final p in ring.cast<List<dynamic>>())
                (p[0] as num).toDouble(),
            ],
            [
              for (final p in ring.cast<List<dynamic>>())
                (p[1] as num).toDouble(),
            ],
          ),
      ];
    } on FormatException catch (e) {
      throw CatalogCorruptedException('Invalid world land data format: $e');
    } on TypeError catch (e) {
      throw CatalogCorruptedException('Invalid world land data format: $e');
    }
  }
}
